### ISSUE TITLE
Converting cerebellar segmentations back to subject space

### ISSUE THREAD

**Issue by rachnasann** [jdiedrichsen/suit#17]
Hi, In our lab, we were able to complete segmentations on SUIT using SPM/Matlab and obtain txt files from suit_lobuli_summarize. The txt files, however, have the same corresponding values for 'size' under each region 1-34. The 'nanmean' values differ, but we are unsure what meaning these values have for analysis? 

We tried to convert back to subject space to obtain comparable sizes (instead of normalized values in the current txt files), but this pipeline does not seem to be working. Any thoughts/help regarding this would be appreciated as we are trying to finish up this project. Thank you!

**Comment by lmidriganciochina** [comment]
Thanks for the developing this tool and making it available!

I have a similar question. I am interested in obtaining ROI volumetric information on brain regions in subject space, to be compared across groups. I have performed isolation, segmentation, and normalization (suit_normalize_dartel) and reslicing to subject space (suit_reslice_dartel_inv).
( NOTE:  if I use the suit_reslice_dartel_inv, versus the SPM option to warp back to subject space, I get different information when summarizing the data; ) 
 Finally, I used the suit_ROI_summarize to obtain volume information, and as described by @rachnasann, the size is the same across participants, while the mean, max and nanmean are different. 
I have, hence, few questions;
1. Why is size information still the same after reslicing to subject space? Is the logic I follow, wrong? 
2. Is there a way to obtain summary info without normalization - which seems counterintuitive?
Thanks!

**Comment by jdiedrichsen** [comment]
Sorry for the long delay - 
Yes, suit_lobuli_summarize returns the size of the ROI as it is defined in the ATLAS file. 

If you want to get the volumes of lobules in individual subject space, you need to inversely reslice the SUIT altas into individual space (be careful to use the nearest neighbour interpolation) and then run the routine seperately for each subject. 

When calling: 
suit_ROI_summarize(images,'atlas','Lobules-SUIT.nii'); 
make sure that the <images> and the <atlas> are in the same space (either SUIT, MNI, or inidivdual) otherwise you will get invalid results.

**Comment by lmidriganciochina** [comment]
Dear Jorn, 
Thank you so much for the reply, I really appreciate you taking the time to get back to me! 
Thanks!

Milly M. C.
